### PR TITLE
[RE-0002] Added initial ROOT-migrate proposal.

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
TODO: What about the discussion thread in the forum? There is no `root-evolution` category from what I see.

**Comment by vgvassilev** [comment]
That's a good question. Lets defer it to @Axel-Naumann.

**Comment by Axel-Naumann** [comment]
Can we use https://root-forum.cern.ch/c/my-root-app-and-ideas ?

**Comment by vgvassilev** [comment]
That section seems much more abstract than what we have as a goal here. I'd personally prefer that we have a new dedicated section about these proposals.

**Pull request merged**
